### ISSUE TITLE
Compare with other libraries (e.g. OpenCV, Ceres-solver)

### ISSUE THREAD

**Issue by ShenghaoZhou** [facebookresearch/ocean#35]
Thanks for sharing this library! This library's cross-platform ability looks very appealing. 

Since its computer vision capability (e.g. feature tracking, camera calibration, PnP) has a great overlap with OpenCV, and its pose optimization has an overlap with Ceres-solver, it would be great to have a discussion to compare with them in the documentation. This can be a good motivation for users to use this library over these popular existing solutions.

My guess is that Ocean intends to provide a self-contained solution without extra dependency on OpenCV or Ceres-solver.  It looks like it can be made to be cross-platform out-of-box, which is definitely a nice thing. 

However, these libraries can be made cross-platform with some effort as well, and they are known to be highly optimized. A performance benchmark would be a good thing to have.

**Comment by leapally** [comment]
Thanks for the suggestion, @ShenghaoZhou!

We do have `testopencv` (path linked below) which is intended to make some comparisons between Ocean and OpenCV.  Though OpenCV needs to be built in order to get the test working.

https://github.com/facebookresearch/ocean/tree/main/impl/application/ocean/test/cv/testcv/testopencv

There may be value in expanding `testopencv` or creating benchmarks for comparison against Ceres-solver.  I'll see if there is bandwidth in the team for that.

**Comment by ShenghaoZhou** [comment]
Thanks for the reply! I appreciate your effort for benchmarking. 

Besides that, I still would like to hear your opinion on the motivation for this project (i.e. what is the main value Ocean brings to the user, that distinguishs itself from other alternatives). 
For example, if Ocean aims to provide a self-contained library that can run cross-platform seamlessly, that would be very amazing already, and users like me would be interested in it. 

While I was amazed by rich features provided by the library, I got a little lost on the main focus of the project.  I saw "high-performance", "low binary impact", "cross-platform" and "rich feature set" mentioned in the front and introduction page. But I was still not sure how it was different from other libraries (e.g. OpenCV). By comparing with other libraries, I mean comparing features offered by the library, as an argument that why Ocean is unique. For example, Ocean may aim to provide AR related vision features similar to OpenCV, but nothing else, thus it can produce smaller binary. Or Ocean may focus on portablility and is easier to get it to work on different platforms than OpenCV.   

Of course, the benchmark is still good to have, as it can help to see the performance.

**Comment by leapally** [comment]
> While I was amazed by rich features provided by the library, I got a little lost on the main focus of the project. I saw "high-performance", "low binary impact", "cross-platform" and "rich feature set" mentioned in the front and introduction page. But I was still not sure how it was different from other libraries (e.g. OpenCV). By comparing with other libraries, I mean comparing features offered by the library, as an argument that why Ocean is unique. For example, Ocean may aim to provide AR related vision features similar to OpenCV, but nothing else, thus it can produce smaller binary. Or Ocean may focus on portablility and is easier to get it to work on different platforms than OpenCV.

Ocean is geared toward creating executables that are performant and has low binary size.

There is a particular focus on enabling users to minimize binary size of static builds of executables.

If, for example, your application only needs Ocean to be able to convert images in pixel format RGB24 to YUV24, you can use `Ocean::CV::FrameConverterRGB24::convertRGB24ToYUV24()`.  And if you link against static build of "ocean_cv" library in order to use the function in your application, the build process will remove most of what's in the "ocean_cv" library that your application dose not use.

This is how static linking works regardless of what library you are using, of course.  So the fact that unused parts of the library does not end up in executables statically linked executables is not a surprise.  But because this is Ocean's focus from the get-go, getting your application's binary size to be as small as possible with reasonable amount of effort should be easier when using Ocean vs something like OpenCV.

> Of course, the benchmark is still good to have, as it can help to see the performance.

I've discussed the possibility of working on benchmarks with the team.  Unfortunately, our resources are constrained at the moment so there's no telling when we will be able to get around to it.

**Comment by ShenghaoZhou** [comment]
Thanks for your explanation! This feature is awesome. 
No worry about the benchmark, I understand there are other priorities.
Thanks again for this great library!
